# Generated by Django 4.0.2 on 2022-03-09 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_post',
            name='photo',
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='member_images/')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.create_post')),
            ],
        ),
    ]
